### ISSUE TITLE
App crashes when I want to create shortcut - Simple Bitcoin Widget version 6.8.3

### ISSUE THREAD

**Issue by chrisbarth01** [hwki/SimpleBitcoinWidget#51] opened 2019-05-30 02:37 UTC
#### Expected behavior 
I expected a shortcut to the widget app I selected to be created when I clicked on 'create shortcut'

---

#### Actual behavior 
When I try to create a shortcut to a widget app, the app crashes. 

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Please note that the crash occurs when I'm creating the shortcut to a widget app. Therefore, you need a widget app (you can download one to reproduce the bug).
- Try adding a shortcut to any of your widget apps (not to the widget app's feature). A shortcut to the app itself. 
- Observe the bug.

---

Device: Gionee f100s 
Android version: v6.0
App version: v6.8.3

---

#### Recording of the bug
- https://youtu.be/EJ32IZdU18c

---

**Comment by hwki** [comment] 2019-05-30 17:29
I'm not sure what the intended behavior should be. By launching the activity directly, you wouldn't be able to create a widget that way anyway. When you create a new widget normally through the launcher, the system gives it a position, size, and an identifier before launching the app's activity and providing it that information. After finishing the activity, the launcher creates the final widget. By launching the activity directly, nothing would happen after hitting save.

I actually handle this in my code by closing the activity immediately. I have to keep the activity "exported" (and therefore, viewable in your activity launcher list) so that certain other devices/launchers are able to create the widget.

The crash appears to be from the launcher's side, I'm not sure what behavior it is expecting.

**Closed** 2019-05-30 20:15 UTC
