### ISSUE TITLE
Infinite loading after phone restart

### ISSUE THREAD

**Issue by othbert** [hwki/SimpleBitcoinWidget#66] opened 2020-05-14 12:15 UTC
Environment:
Samsung Galaxy S10e & Sony Xperia XZ1 Compact
Android 10 & 9
2 widgets on same homescreen. 

Tested with combinations of ETH & XRP @ Binance & Kraken

To replicate:
When restarting the phone, the widget loader spins indefinitely instead of displaying the price.
Tapping does not refresh. Widgets may eventually come back after several **days**.

Workaround:
The only surefire way I've found to get the widgets back is to add another dummy one to a homescreen, setting any currency/exchange pair, any display options, confirm it, wait for it to load information, and the others that were spinning will load too. Then the dummy one can be deleted.

Love the app, been using it (and previously the Simple Ethereum Widget) for ages.
They've both suffered this same issue for me though, I think possibly they always had this issue?

**Comment by hwki** [comment] 2020-05-14 12:59
This is a duplicate of https://github.com/hwki/SimpleBitcoinWidget/issues/39. Unfortunately I can't reliably reproduce this issue in order to look into it. I have seen it myself a few times, but rarely. It doesn't occur for me on any restart, but I have seen it a couple times after a security patch update. If you have any other information that could help me reproduce it that would be great (e.g. are your devices connected to wifi or mobile data, and what type? any data saver/ battery saver settings turned on? airplane mode, etc.)

**Comment by othbert** [comment] 2020-05-14 13:14
Hmm, are you sure? I checked that one but seems different. In my case, I don't get any greyed out behaviour at all. It shows the placeholder white background where the widget will load, then when the homescreen begins to redraw the widgets, it jumps straight to an infinite loader. No interaction causes any update. 
Anyway, it happens without fail after a phone restart for me. Wifi connection. No data saving / battery saving settings on. No airplane mode.
This s10e is a pretty new phone for me so I've not installed much on it really. I'm using Nova launcher if that makes a difference, with multiple widgets on center (default) homescreen.

**Comment by hwki** [comment] 2020-05-14 13:56
I think its the same problem but it might not be, since I can't reproduce it. Thats what makes it frustrating, I have an s9 and a pixel 2, and use nova launcher, but can't see the same behavior.

How often do you have these widgets set to refresh? And if it happens often for you, would you be willing to try out a debug build if I sent one your way, to gather some logs?

**Comment by othbert** [comment] 2020-05-14 14:28
I don't see a way to check the settings after having added them, but pretty sure I never bothered to change it from the default, so 30mins I'm guessing.
I could try a debug build on the Xperia XZ1c, sure.

**Comment by hwki** [comment] 2020-05-14 16:13
Great, thanks @othbert. could you send me an email at apps@brentpanther.com so I can send you a build please?

**Closed** 2020-08-30 16:28 UTC
