### ISSUE TITLE
text showing too large

### ISSUE THREAD

**Issue by frederiiiic** [hwki/SimpleBitcoinWidget#36] opened 2018-01-18 20:36 UTC
Hi there,
i've just installed the widget, and prices is showing too large that i can't see anything.

Like this : 
![screenshot_20180118-213314](https://user-images.githubusercontent.com/10772930/35120492-9830cd04-fc98-11e7-97ca-8ce01cfa6434.png)

**Comment by hwki** [comment] 2018-01-22 12:39
@frederiiiic 
I need some more info to start looking at the problem. Can you provide the following please:
Android version
Phone
Launcher used
Exchange selected
Currency
Anything else that might be configured out of the ordinary.

**Comment by frederiiiic** [comment] 2018-01-22 18:25
Yes sure, i'v do it too fast.

Android v 6.0.1 (Fairphone Open OS 18.01.1)
Phone Fairphone 2 (FP2)
Launcher OpenLauncher v0.5.8
Exchange selected Coinbase
Currency BTC/USD

**Comment by frederiiiic** [comment] 2018-01-22 19:52
Maybe can we put an issue to them.

**Comment by hwki** [comment] 2018-02-28 15:14
Closing this, appears to be caused by this bug on OpenLauncher: https://github.com/OpenLauncherTeam/openlauncher/issues/30 linked from https://github.com/OpenLauncherTeam/openlauncher/issues/281

**Closed by hwki** 2018-02-28 15:14 UTC
